### ISSUE TITLE
Is there a reason for multiDexEnabled?

### ISSUE THREAD

**Issue by flyingmate** [Neson/react-native-system-notification#1]
Usually multiDexEnabled increases android build time.
does this library overflow the limit of method number of single dex compilation?

**Comment by Neson** [comment]
Hmmm, right - it isn’t required to set multiDexEnabled for this package to work. It is there just because I’ve ran into that problem when I start writing this package - in another complex project.

I’ll move it to a _hint_ section in the README. Thanks for your feedback! :smile:

**Comment by flyingmate** [comment]
Cool!
