### ISSUE TITLE
react-native-system-notification and react-native-gcm-android peer depend upon incompatible versions of each other

### ISSUE THREAD

**Issue by Longsight** [Neson/react-native-system-notification#43]
```
$ npm i --save react-native-gcm-android
[snip]
├── react-native-gcm-android@0.2.0 
└── UNMET PEER DEPENDENCY react-native-system-notification@^0.1.2

npm WARN react-native-gcm-android@0.2.0 requires a peer of react-native-system-notification@^0.1.2 but none was installed.
```
```
$ npm i --save react-native-system-notification
[snip]
├── UNMET PEER DEPENDENCY react-native-gcm-android@0.2.0
└── react-native-system-notification@0.1.10 

npm WARN react-native-system-notification@0.1.10 requires a peer of react-native-gcm-android@^0.1.9 but none was installed.
```
This appears to be down to peer dependency version mismatching, as ^0.1.9 refers to ">=0.1.9 < **0.2.0**" rather than ">=0.1.9 < 1.0.0".

`$ npm i --save react-native-system-notification@0.1.8` works as expected, as `react-native-system-notification@0.1.8` depends upon `react-native-gcm-android@0.2.0`, whereas all `react-native-gcm-android@0.1.x` versions depend upon `react-native-system-notification@0.0.8` or lower.

**Comment by Neson** [comment]
Thanks for reporting! I didn't noticed that gcm-android has already bumped to 0.2.x.

**Comment by Neson** [comment]
Closing in favor of PR :)
