### ISSUE TITLE
Support of expanded notification

### ISSUE THREAD

**Issue by alvinthen** [Neson/react-native-system-notification#5]

**Comment by Neson** [comment]
Thanks for your feedback! This feature is on the roadmap as to support all Android notification features, but I'm not sure when will I go ahead to implement it.

**Comment by julianocomg** [comment]
Why not just set expanded styles for all notifications? The notification message are being truncated :cry: 

http://developer.android.com/guide/topics/ui/notifiers/notifications.html#ApplyStyle

**Comment by julianocomg** [comment]
Well, I made a PR #14

**Comment by Neson** [comment]
Closing this and thanks for the PR!
