### ISSUE TITLE
iOS red screen - EventEmitter

### ISSUE THREAD

**Issue by FlorianeEnnaji** [Neson/react-native-system-notification#6]
Launching the app in iOS makes a red screen, error message being "Unable to resolve module EventEmitter from /User/.../node_modules/react-native-system-notification/index.js: Invalid directory /Users/node_modules/EventEmitter"
However, I noticed that variable EventEmitter is declared but not used in index.js

**Comment by Neson** [comment]
Oh, I will remove that `EventEmitter `.

BTW, PRs are welcome if you'd already done & tested that on your local copy!

**Comment by Neson** [comment]
Thanks :wink:
