### ISSUE TITLE
Cannot get notification payload by clicking notification with the app killed.

### ISSUE THREAD

**Issue by oney** [Neson/react-native-system-notification#9]
Please see these discussions https://github.com/oney/react-native-gcm-android/pull/19#issuecomment-172503426
We can't get notification payload by clicking notification with the app killed.
Attaching the payload of the notification to `popInitialNotification` is better implementation. The iOS implementation is [here](https://github.com/facebook/react-native/blob/cb45eaa0e8cab0f8a4b1c507494b0483e344b682/Libraries/PushNotificationIOS/PushNotificationIOS.js#L242)

**Comment by RGBz** [comment]
:+1:

**Comment by mtford90** [comment]
+1

**Comment by Neson** [comment]
The implementation is done now in 6c418f, for now the initial notification payload should be get immediately after registering the `press` callback. Does it work as expect with this approach?
